import math
import os

import cadquery as cq

from geometry import CAV_H, L, OUT, P, T_PLATE, Z_TOP
from puck_parts import port_numbers

NAMES = ["plate (6061)", "standoffs (Al)", "pcb (FR4)", "sleeve (steel)", "cell LIR1254", "module BMD-340",
         "USB-C connector", "other SMD parts", "cap (PC)"]
STL = {"tolerance": 0.02, "angularTolerance": 0.1}
COLORS = {"plate": (0.25, 0.25, 0.28), "standoffs": (0.75, 0.75, 0.78), "cap": (0.85, 0.9, 1.0, 0.35),
          "pcb": (0.1, 0.4, 0.15), "sleeve": (0.7, 0.7, 0.72),
          "cell": (0.8, 0.8, 0.8), "module": (0.2, 0.2, 0.2), "connector": (0.9, 0.7, 0.2)}
STL_PARTS = ("plate", "cap", "sleeve", "standoffs")


def totals(items):
    m = sum(i[0] for i in items)
    mx = sum(i[0] * i[1][0] for i in items)
    my = sum(i[0] * i[1][1] for i in items)
    mz = sum(i[0] * i[1][2] for i in items)
    return m, mx, my, mz


def header_lines():
    c = L["cell"]
    skin, flat_w = port_numbers()
    return [
        "ShotPuck mass & balance report (generated by puck.py)\n",
        f"Overall: OD {P['od']:.1f} mm, height above the weight face {Z_TOP:.2f} mm "
        f"({T_PLATE:.1f} mm flat plate); {L['bolt']['thread']} bolt through the D{L['sleeve']['od']:.0f} mm sleeve",
        f"PCB on {P['pcb_standoff']:.1f} mm standoffs; cell on the Kapton in the PCB notch: {CAV_H:.2f} mm to the "
        f"ceiling (cell {c['h']:.1f} mm + {CAV_H - c['h']:.1f} mm free)",
        f"USB-C port: {skin:.2f} mm of cap top left over the connector; plug flat {flat_w:.1f} mm wide "
        f"(overmold max {L['connector']['overmold_w']:.2f} mm)\n",
        f"{'part':22s}{'mass g':>9s}{'x':>8s}{'y':>8s}{'z':>8s}",
    ]


def balance_lines(items):
    m, mx, my, mz = totals(items)
    return [f"\nTotal mass: {m:.2f} g",
            f"Centre of mass: x={mx / m:.3f} y={my / m:.3f} z={mz / m:.2f} mm -> "
            f"{math.hypot(mx, my) / m:.3f} mm off axis ({math.hypot(mx, my):.2f} g*mm)",
            "\nComponent masses are datasheet/estimated values from layout.json. Weigh the real parts and re-run."]


def write_report(items):
    rep = header_lines()
    for name, (mm, c) in zip(NAMES, items):
        rep.append(f"{name:22s}{mm:9.2f}{c[0]:8.2f}{c[1]:8.2f}{c[2]:8.2f}")
    rep += balance_lines(items)
    open(os.path.join(OUT, "mass_report.txt"), "w").write("\n".join(rep) + "\n")
    print("\n".join(rep))


def export(parts):
    for name in ("plate", "cap"):
        cq.exporters.export(parts[name], os.path.join(OUT, name + ".step"))
    for name in STL_PARTS:
        cq.exporters.export(parts[name], os.path.join(OUT, name + ".stl"), **STL)
    assy = cq.Assembly(name="shotpuck")
    for name, color in COLORS.items():
        assy = assy.add(parts[name], name=name, color=cq.Color(*color))
    assy.save(os.path.join(OUT, "assembly.step"))
